id:
  - infra
  - agent
name: Infrastructure Agent Linux Installer
description: New Relic install recipe for the Infrastructure agent
repository: https://github.com/newrelic/infrastructure-agent

# tag convention for dealing with search terms that could land someone on this instrumentation project
tags:
  - infrastructure
  - agent

# Examine Infrastructure events for correlated data
process_match:
 - /infra/

# Examine Metrics, Events, and Logging for correlated data
# Used by the UI to determine if you've successfully configured and are ingesting data
melt_match:
 events:
   - pattern: /SystemSample/
 metrics:
   - pattern: /system.cpu.usage/
 logging:
   - pattern: /http/
      files:
        - /var/log/system.log