# Visit our schema definition for additional information on this file format
# https://github.com/newrelic/open-install-library/blob/main/docs/recipe-spec/recipe-spec.md#schema-definition

name: infrastructure-agent-installer
displayName: Infrastructure Agent
description: New Relic install recipe for the Infrastructure agent
repository: https://github.com/newrelic/infrastructure-agent

installTargets:
  - type: host
    os: linux
    platform: "debian"

keywords:
  - Infrastructure
  - Agent
  - Linux
  - Debian
  - Jessie
  - Stretch
  - Buster

processMatch: []

validationNrql: "SELECT count(*) from SystemSample where hostname like '{{.HOSTNAME}}' FACET entityGuid SINCE 10 minutes ago"

install:
  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: assert_pre_req
        - task: setup_license
        - task: install_infra
        - task: restart

    assert_pre_req:
      cmds:
        - |
          IS_GREP_INSTALLED=$(which grep | wc -l)
          if [ $IS_GREP_INSTALLED -eq 0 ] ; then
            echo "grep is required to run the newrelic install. Please install grep and re-run the installation." >> /dev/stderr
            exit 10
          fi
        - |
          IS_SED_INSTALLED=$(which sed | wc -l)
          if [ $IS_SED_INSTALLED -eq 0 ] ; then
            echo "sed is required to run the newrelic install. Please install sed and re-run the installation." >> /dev/stderr
            exit 11
          fi
        - |
          IS_AWK_INSTALLED=$(which awk | wc -l)
          if [ $IS_AWK_INSTALLED -eq 0 ] ; then
            echo "awk is required to run the newrelic install. Please install awk and re-run the installation." >> /dev/stderr
            exit 12
          fi
        - |
          IS_INFRA_AVAILABLE=$(curl -Is https://download.newrelic.com/infrastructure_agent/linux/apt/dists/{{.DEBIAN_CODENAME}}/InRelease | grep " 200 " | wc -l)
          if [ $IS_INFRA_AVAILABLE -eq 0 ] ; then
            echo "there is no newrelic infrastructure agent available for the distribution '{{.DEBIAN_CODENAME}}'." >> /dev/stderr
            exit 13
          fi
      vars:
        DEBIAN_CODENAME:
          sh: cat /etc/os-release | grep VERSION_CODENAME | awk -F = '{print $2}'

    setup_license:
      cmds:
        - |
          if [ -f /etc/newrelic-infra.yml ]; then
            sudo rm /etc/newrelic-infra.yml;
          fi
          sudo touch /etc/newrelic-infra.yml;
        - |
          sudo tee /etc/newrelic-infra.yml > /dev/null <<"EOT"
          license_key: {{.NEW_RELIC_LICENSE_KEY}}
          enable_process_metrics: true
          EOT
        - |
          if [ $(echo {{.NEW_RELIC_REGION}} | grep -i staging | wc -l) -gt 0 ]; then
            echo 'staging: true' | sudo tee -a /etc/newrelic-infra.yml > /dev/null
          fi

    install_infra:
      cmds:
        - sudo apt-get update -yq
        - sudo apt-get install gnupg2 -y
        - sudo curl -s https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg | sudo apt-key add -
        - printf "deb [arch=amd64] https://download.newrelic.com/infrastructure_agent/linux/apt {{.DEBIAN_CODENAME}} main" | sudo tee -a /etc/apt/sources.list.d/newrelic-infra.list > /dev/null
        - sudo apt-get update -yq
        - sudo apt-get install newrelic-infra -y -qq
      vars:
        DEBIAN_CODENAME:
          sh: cat /etc/os-release | grep VERSION_CODENAME | awk -F = '{print $2}'
      silent: true

    restart:
      cmds:
        - sudo systemctl restart newrelic-infra.service

postInstall:
  info: |2
      ⚙️  The Infrastructure Agent configuration file can be found in /etc/newrelic-infra.yml
      Edit this file to make changes or configure advanced features for the agent. See the docs for options:
      https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings
      
      Note: Process monitoring has been enabled by default - all other config options are left to the user.
