name: Cleanup

on:
  workflow_run:
    workflows: [Tests]
    types: [completed]

jobs:
  env:
    workflow_run_id: ${{ context.payload.workflow_run.id }}
    config_name: gitusdkr${{ context.payload.workflow_run.id }}.json
    path: test/definitions/smoke
    is_eu: false
  clean-all:
    name: Cleaner
    runs-on: ubuntu-latest
    steps:
      - name: Debug run_id
        run: |
          echo "Debugging env vars here"
          echo "workflow_run_id:"$workflow_run_id
          echo "config_name:"$config_name
          echo "path":$path
          echo "is_eu:"$is_eu

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Write AWS Certificate to File
        env:
          AWS_PEM: ${{ secrets.GIT_DEPLOYER_CANADA_AWS_PEM }}
        run: |
          mkdir -p configs
          rm -f configs/gitdeployerCanada.pem
          echo "$AWS_PEM" > configs/gitdeployerCanada.pem
          sudo chmod 400 configs/gitdeployerCanada.pem

      - name: Write Test Definition File JSON to file
        if: $is_eu == false
        env:
          USER_JSON: ${{ secrets.GIT_DEPLOYER_DOCKER_USER_CONFIG }}
        run: |
          echo "$USER_JSON" > configs/$config_name

      - name: Write Test Definition File JSON to file EU
        if: $is_eu
        env:
          USER_JSON: ${{ secrets.GIT_DEPLOYER_DOCKER_USER_CONFIG_EU }}
        run: |
          echo "$USER_JSON" > configs/$config_name

      - name: Pull Deployer image
        run: |
          docker pull ghcr.io/newrelic/deployer:latest
          docker images ghcr.io/newrelic/deployer:latest

      - name: Teardown all resources
        run: |
          docker run -i\
            -v ${{ github.workspace }}/configs/:/mnt/deployer/configs/\
            -v ${{ github.workspace }}/test/:/mnt/deployer/test/\
            --entrypoint ruby ghcr.io/newrelic/deployer:latest batch.rb -c configs/$config_name -d $path -s 20 -m teardown
