name: Limit PRs on local repo only for E2E tests

on:
  pull_request:
    branches:
      - main

jobs:
  limit_main_pr:
    runs-on: ubuntu-latest
    steps:
      # 1) Check for all incoming changes to files under `recipes` directory
      - name: Ensure no fork repo
        run: |
          IS_REMOTE=$(echo ${{ github.event.pull_request.base.ref }} | grep ":" | wc -l)
          if [ $IS_REMOTE -gt 0 ] ; then
            echo "PR should be created from a branch on the source repo, not from a fork, so the E2E tests can run"
            exit 1
          fi
