on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Release Changes
        id: recentCommits
        run: |
          echo ::set-output name=release_body::$(git log --no-merges --pretty=format:'%s' $(git describe --abbrev=0 --tags)...HEAD)
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{steps.recentCommits.outputs.release_body}}
          draft: false
          prerelease: false

  zip-recipes:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Write version
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: recipes/version.txt
          contents: $tag_name
          write-mode: overwrite
          tag_name: ${{ steps.get_release.outputs.tag_name }}

      - name: Zip recipes
        uses: papeloto/action-zip@v1
        with:
          files: recipes/ version.txt
          dest: recipes.zip

      - name: Upload recipes zip file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/recipes.zip
          asset_name: recipes.zip
          asset_content_type: application/octet-stream
